name: 'Build project with CMake'
inputs:
  cmake-arguments:
    description: |
      Additional CMake configuration arguments
      They will be split by whitespace characters before feeding them into CMake
    required: false
    default: ''
  package:
    description: 'Build package target'
    required: false
    default: 'false'
outputs:
  build-directory:
    description: Build directory
runs:
  using: 'node16'
  main: 'dist/index.js'
