name: 'Build project with CMake'
inputs:
  cmake-arguments:
    description: |
      Additional CMake configuration arguments
      They will be split by whitespace characters before feeding them into CMake
    required: false
    default: ''
  output-directories-suffix:
    description: 'Build/install directories suffix'
    required: false
    default: ''
  install:
    description: 'Run install step'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
